queue_rules:
  - name: hotfix
    queue_conditions:
      - label=hotfix
      - check-success=default
    merge_method: squash

  - name: default
    branch_protection_injection_mode: merge
    queue_conditions:
      - or:
        - schedule=Mon-Fri 20:00-23:59[America/Los_Angeles]
        - schedule=Mon-Fri 00:00-7:00[America/Los_Angeles]
    merge_method: squash
    

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label=queue
    actions:
      queue:
      merge:
        method: squash
