queue_rules:
  - name: hotfix
    queue_conditions:
      - label=hotfix
      - check-success=default
    merge_method: squash

  - name: default
    branch_protection_injection_mode: merge
    queue_conditions:
      - schedule=21:50-23:59[America/Los_Angeles]
    merge_method: squash
