queue_rules:
  - name: hotfix
    queue_conditions:
      - label=hotfix
      - check-success=default
    merge_method: squash

  - name: default
    queue_conditions:
      - check-success=default
    merge_conditions:
      - "approved-reviews-by>=1"
    merge_method: squash
    

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label=queue
    actions:
      queue:
      merge:
        method: squash
