queue_rules:
  - name: hotfix
    queue_conditions:
      - label=hotfix

  - name: default
    queue_conditions:
      - label=default
    merge_conditions:
      - "approved-reviews-by>=2"

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label=queue
    actions:
      queue:
