name: Comment "rushins-test" on Draft PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Comment on Draft PR by "rushinshah85"
        if: ${{ github.event.pull_request.draft == true && github.event.pull_request.user.login == 'rushinshah85' }}
        run: |
          prNumber="${{ github.event.pull_request.number }}"
          comment="rushins-test"

          echo "::set-env name=prNumber::$prNumber"
          echo "::set-env name=comment::$comment"

      - name: Post Comment
        if: env.prNumber && env.comment
        run: |
          echo "Posting comment..."
          echo "$env.comment"
          gh pr comment $env.prNumber -b "$env.comment"
