name: Comment "rushins-test" on Draft PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Comment on Draft PR by "rushins"
        if: ${{ github.event.pull_request.draft == true && github.event.pull_request.user.login == 'rushinshah85' }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMENT_TEXT: 'rushins-test'
        run: |
          echo "Posting comment..."
          echo "$COMMENT_TEXT"
          gh pr comment $PR_NUMBER -b "$COMMENT_TEXT"
